import pandas as pd
import numpy as np
import os
import json

def run_profit_mapping(data_dir="atlas/data", model_dir="atlas/models"):
    print("🚀 Phase 6: Profitability Mapping...")
    
    # 1. Load Data
    states_path = os.path.join(data_dir, "market_states.parquet")
    outcomes_path = os.path.join(data_dir, "outcomes.parquet")
    mapping_path = os.path.join(data_dir, "trade_clusters.parquet")
    
    if not all(os.path.exists(p) for p in [states_path, outcomes_path, mapping_path]):
        print("❌ Error: Required datasets for mapping not found!")
        return
        
    df_states = pd.read_parquet(states_path)
    df_outcomes = pd.read_parquet(outcomes_path)
    df_mapping = pd.read_parquet(mapping_path)
    
    # 2. Join Everything
    # We join all three to have State Features + Outcomes + ClusterID
    # NOTE: 'trade_clusters.parquet' is now generated by atlas_profiler (K-Means 12)
    print("🔗 Joining datasets via trade_id...")
    df = df_states.merge(df_mapping, on='trade_id')
    df = df.merge(df_outcomes, on='trade_id', suffixes=('', '_out'))
    
    # 3. Aggregate by Cluster
    print("📊 Computing regime statistics...")
    
    # Group by cluster_id, action, style as per plan
    # Actually, the user's ClusteringAtlas.md says (cluster_id, action, style)
    # This allows us to see how REMR performs in Cluster X vs ITC in Cluster X.
    
    groups = df.groupby(['cluster_id', 'action', 'style'])
    
    stats = groups.agg({
        'pnl_points': ['mean', 'std', 'count'],
        'mae': 'mean',
        'mfe': 'mean',
        'bars_held': 'mean'
    }).reset_index()
    
    # Flatten columns
    stats.columns = [
        'cluster_id', 'action', 'style', 
        'exp_pnl', 'pnl_std', 'sample_size', 
        'risk_mae', 'risk_mfe', 'avg_bars'
    ]
    
    # Calculate Win Rate (PnL > 0)
    # Need to do this separately as it's not a simple agg
    def get_win_rate(group):
        pos_pnl = (group['pnl_points'] > 0).sum()
        total = len(group)
        return pos_pnl / total if total > 0 else 0.0
        
    win_rates = groups.apply(get_win_rate, include_groups=False).reset_index()
    win_rates.columns = ['cluster_id', 'action', 'style', 'win_rate']
    
    stats = stats.merge(win_rates, on=['cluster_id', 'action', 'style'])
    
    # 4. Filter Noise
    # We keep noise (-1) in the stats for reference, but mostly care about 0..N
    
    # 5. Export Atlas World Model
    stats_json = stats.to_dict(orient='records')
    output_path = os.path.join(model_dir, "cluster_stats.json")
    
    # Structure for runtime querying
    world_model = {
        "version": "2.8.3-Authoritative",
        "timestamp": str(pd.Timestamp.now()),
        "total_probes": int(len(df)),
        "regimes": stats_json
    }
    
    with open(output_path, 'w') as f:
        json.dump(world_model, f, indent=4)
        
    print(f"✅ SUCCESS: Mapped profitability for {len(stats)} regime/action/style combinations.")
    print(f"💾 World Model saved to {output_path}")

if __name__ == "__main__":
    run_profit_mapping()
